/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as ChatThreadIdRouteImport } from './routes/chat.$threadId'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiSttRouteImport } from './routes/api/stt'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiImageRouteImport } from './routes/api/image'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageRoute = ApiImageRouteImport.update({
  id: '/api/image',
  path: '/api/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/integrations': typeof IntegrationsRoute
  '/memories': typeof MemoriesRoute
  '/settings': typeof SettingsRoute
  '/voice': typeof VoiceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/image': typeof ApiImageRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/integrations': typeof IntegrationsRoute
  '/memories': typeof MemoriesRoute
  '/settings': typeof SettingsRoute
  '/voice': typeof VoiceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/image': typeof ApiImageRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/chat': typeof ChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/integrations': typeof IntegrationsRoute
  '/memories': typeof MemoriesRoute
  '/settings': typeof SettingsRoute
  '/voice': typeof VoiceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/image': typeof ApiImageRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/integrations'
    | '/memories'
    | '/settings'
    | '/voice'
    | '/api/chat'
    | '/api/image'
    | '/api/mcp'
    | '/api/stt'
    | '/api/tts'
    | '/chat/$threadId'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/integrations'
    | '/memories'
    | '/settings'
    | '/voice'
    | '/api/chat'
    | '/api/image'
    | '/api/mcp'
    | '/api/stt'
    | '/api/tts'
    | '/chat/$threadId'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/integrations'
    | '/memories'
    | '/settings'
    | '/voice'
    | '/api/chat'
    | '/api/image'
    | '/api/mcp'
    | '/api/stt'
    | '/api/tts'
    | '/chat/$threadId'
    | '/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntegrationsRoute: typeof IntegrationsRoute
  MemoriesRoute: typeof MemoriesRoute
  SettingsRoute: typeof SettingsRoute
  VoiceRoute: typeof VoiceRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiImageRoute: typeof ApiImageRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiSttRoute: typeof ApiSttRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image': {
      id: '/api/image'
      path: '/api/image'
      fullPath: '/api/image'
      preLoaderRoute: typeof ApiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntegrationsRoute: IntegrationsRoute,
  MemoriesRoute: MemoriesRoute,
  SettingsRoute: SettingsRoute,
  VoiceRoute: VoiceRoute,
  ApiChatRoute: ApiChatRoute,
  ApiImageRoute: ApiImageRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiSttRoute: ApiSttRoute,
  ApiTtsRoute: ApiTtsRoute,
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
